### ISSUE TITLE
[BUG] Crash when pasting deform key from node that has it to node that doesn't have it

### ISSUE THREAD

**Issue by ShatReal** [Inochi2D/inochi-creator#196] opened 2023-03-04 14:58 UTC
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

I was trying to make the same deform on eye right as eye left, so I tried copying and pasting it.

### Reproduction

1. Make one deform keyframe.
2. Make another keyframe without deform on another node.
3. Copy the deform keyframe.
4. Try to paste it onto the other node.

### System Architecture

None

### Operating System

Windows

### Version

commit+757eb65

**Comment by LunaTheFoxgirl** [comment] 2023-04-25 17:50
I am unable to reproduce this issue at all. I'll close it for now. If you find a way to reproduce the issue I can reopen this issue.

**Closed by LunaTheFoxgirl** 2023-04-25 17:50 UTC
Labels: Bug
