### ISSUE TITLE
[BUG] Dragging nodes can cause crashes in the Nodes tab

### ISSUE THREAD

**Issue by ATWReferences** [Inochi2D/inochi-creator#162] opened 2023-01-15 09:39 UTC
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

In an attempt to learn how to use Inochi I was playing around with the buttons while reading the unofficial docs.  I may have discovered an area in the nodes window where if you drag another node it kills the whole program.  I was moving "left horn merged" back and forth from "unnamed node".  If I drop them on top of each other (sorry, I forget the order) I get a circular dependency error.  But, if I drop one of them on that little yellow rectangle shown in mystery_space.png, Inochi just crashes.

### Reproduction

1. Make a node from a layer in your puppet
2. Drag the new node into the yellow area as highlighted in mystery_space.png
3. Crash

### System Architecture

x86_64

### Operating System

Linux

### Version

0.7.4.1

### Additional Context

[inochi-creator-crashdump.txt](https://github.com/Inochi2D/inochi-creator/files/10419835/inochi-creator-crashdump.txt)
![mystery_space](https://user-images.githubusercontent.com/122722143/212533464-06a60550-5c80-4a08-b363-62e4e8f2b678.png)

**Comment by LunaTheFoxgirl** [comment] 2023-01-15 09:52
This is a known issue but thanks for putting on the issue tracker, will fix it ASAP. Just haven't had the chance to yet orz

**Comment by ATWReferences** [comment] 2023-01-15 10:06
Glad to help

**Comment by LunaTheFoxgirl** [comment] 2023-04-25 09:54
I am unable to reproduce it in the latest nightly build, we did do some restructuring of things, so I assume this is fixed now. Do feel free to make a new issue if the issue crops up again, though.

**Closed by LunaTheFoxgirl** 2023-04-25 09:54 UTC
Labels: Bug
