### ISSUE TITLE
[BUG] Segmentation fault when trying to use "Attempt full repair"

### ISSUE THREAD

**Issue by rilysh** [Inochi2D/inochi-creator#243] opened 2023-04-25 07:42 UTC
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

After creating a new model and adding things like node, mask, composite, etc. when I click on "Attempt full repair" Inochi Creator crashes with segfault. I'm using [v0.7.4.1](https://github.com/Inochi2D/inochi-creator/releases/tag/v0.7.4.1).

Opening Inochi in GDB doesn't seem like it gave any relevant information, however, it crashes when calling the `describeUndo` function.
```
Thread 1 "inochi-creator" received signal SIGSEGV, Segmentation fault.
0x00005555554f8785 in creator.actions.node.NodeMoveAction.describeUndo() ()
```

### Reproduction

1. Open Inochi Creator and create a new project.
2. Add things like Node, Mask, or any other one to that puppet.
3. Go to the "tools" section and click on "Attempt full repair".

### System Architecture

x86_64

### Operating System

Linux

### Version

v0.7.4.1

**Comment by LunaTheFoxgirl** [comment] 2023-04-25 09:40
Seems like I can't reproduce the issue in nightly builds, could you test one of the builds here and see if the issue persists in that?
https://github.com/Inochi2D/inochi-creator/releases/tag/nightly

**Comment by rilysh** [comment] 2023-04-25 11:02
Hi, I tried the nightly build but for some reason, I got a segfault and this time it seems like an issue with GPU(?)
```
GLInfo:
	4.2 (Core Profile) Mesa 20.3.5
	Intel Open Source Technology Center
	Mesa DRI Intel(R) HD Graphics 2500 (IVB GT1)
	4.20
	gls=gl33
[1]    2389 segmentation fault  ./inochi-creator
```
I don't have a discrete GPU....totally rely on iGPU. Here's GDB
```
Thread 1 "inochi-creator" received signal SIGSEGV, Segmentation fault.
0x0000555555760467 in ImGui::FindBlockingModal(ImGuiWindow*) ()
```

**Comment by rilysh** [comment] 2023-04-25 11:13
Yeah, I noticed, but it showed iGPU version and then segfault, so mentioned to make the whole "phrase" quite complete.
Also the backtrace (if needed)
```
#0  0x0000555555760467 in ImGui::FindBlockingModal(ImGuiWindow*) ()
#1  0x000055555576253d in ImGui::Begin(char const*, bool*, int) ()
#2  0x000055555573347b in igBegin ()
#3  0x00005555555c9f63 in creator.widgets.incBegin(const(char)*, bool*, bindbc.imgui.bind.imgui.ImGuiWindowFlags) (name=0x7ffff62660c0 "Viewport###Viewport", 
    pOpen=0x7ffff62561dc, flags=56) at source/creator/widgets/package.d:37
#4  0x000055555564053d in creator.panels.Panel.onBeginUpdate() (
    this=0x7ffff6256180) at source/creator/panels/package.d:40
#5  0x00005555556404cb in creator.panels.viewport.ViewportPanel.onBeginUpdate()
    (this=0x7ffff6256180) at source/creator/panels/viewport.d:45
#6  0x000055555565670d in creator.panels.Panel.update() (this=0x7ffff6256180)
    at source/creator/panels/package.d:120
#7  0x0000555555656830 in creator.panels.incUpdatePanels() ()
    at source/creator/panels/package.d:158
#8  0x000055555573242c in app.incUpdate() () at source/app.d:135
#9  0x0000555555732383 in D main (args=...) at source/app.d:97
```

**Comment by LunaTheFoxgirl** [comment] 2023-04-25 11:34
Ah, related to this ImGui issue, I think https://github.com/ocornut/imgui/issues/5401

**Comment by LunaTheFoxgirl** [comment] 2023-04-25 11:38
Might be fixed by https://github.com/Inochi2D/inochi-creator/commit/275e7e0c2db61c3ff5e5b730fd17920b56704d93, I've triggered a forced nightly build https://github.com/Inochi2D/inochi-creator/actions/runs/4797011848 once this is done could you check if that solves the issue?

**Comment by rilysh** [comment] 2023-04-25 11:53
Looks like after that patch everything is stable right now. I also tried "Attempt full repair" which also worked fine in nightly build. Thank you!

Should I close the issue since it's now fixed for me or keep it open (e.g. for stable builds since they're not updated yet)?

**Closed** 2023-04-25 12:02 UTC
Labels: Bug, Needs verification
