### ISSUE TITLE
[BUG] Mesh editor mirror vertices move the wrong direction when ctrl+dragging

### ISSUE THREAD

**Issue by HigasaMitsue** [Inochi2D/inochi-creator#118] opened 2022-10-17 05:02 UTC
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

When placing a vertex by holding Ctrl and dragging, the vertex moves the wrong direction.
1. When horizontal mirror is enabled, the vertex x-offset is inverted.
2. When vertical mirror is enabled, the vertex y-offset is inverted.
3. When both are enabled, the vertex x-offset is inverted, but the y-offset is correct.

### Reproduction

1. Import any texture
2. Right click > Edit Mesh
3. Enable any mirror in the mesh editor
4. Hold Ctrl and drag the vertex around

### System Architecture

x86_64

### Operating System

Windows

### Version

2dc4fd2

### Additional Context

![out](https://user-images.githubusercontent.com/109067911/196092783-8c4364fa-0764-4b0e-8862-4356f93fd1bf.gif)

**Comment by LunaTheFoxgirl** [comment] 2022-10-17 14:42
Note to self: this is caused by the mirror selecting the wrong vertex to move, as such the movement is mirrored

**Comment by LunaTheFoxgirl** [comment] 2022-10-19 18:17
Fixed by https://github.com/Inochi2D/inochi-creator/commit/7941b12a362690405ac123beb8950e37db9348ae

**Closed by LunaTheFoxgirl** 2022-10-19 18:17 UTC
Labels: bug
