### ISSUE TITLE
[BUG] Hitting undo when manipulating mesh with armed parameter only moves vertices to their initial position

### ISSUE THREAD

**Issue by HoneyBuzzBee** [Inochi2D/inochi-creator#173] opened 2023-02-11 02:26 UTC
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

This one may be related to my previous bug report #171. When I edit a vertex with a parameter armed and hitting ctrl+z or pressing undo from the Edit menu, instead of the vertex going back to the position it was _previously_ it snaps back to the position it was _initially_ before editing the mesh. See attached video for clarification. Curiously when I move around a vertex a few times with the vertex tool, select the path deform tool, draw and edit a path, go back to the vertex tool, make changes to the mesh and **then** hit undo the vertex does properly go back to its previous position. 

### Reproduction

1. Arm a parameter
2. Move a vertex around a couple times
3. Hit undo

### System Architecture

x86_64

### Operating System

Linux

### Version

9e28c3cfaaaecab94fbf39c868a5726600f8cc90

### Additional Context

[Screencast from 2023-02-11 03-23-19.webm](https://user-images.githubusercontent.com/121172411/218234239-27e5a6d5-f870-42e6-b705-892b2135a446.webm)

**Comment by LunaTheFoxgirl** [comment] 2023-02-11 04:55
Vertex modifications stack together, so they'll go back to the initial state before you edited the deformation that time.

Mainly to prevent a massive flow of vertex undos, maybe a slightly more clever stacking algorithm should be made there

**Comment by seagetch** [comment] 2023-02-11 16:18
I cannot reproduce this behavior. In my environment, position is going back to a previous state, not to an initial state.

**Comment by HoneyBuzzBee** [comment] 2023-02-11 16:53
> I cannot reproduce this behavior. In my environment, position is going back to a previous state, not to an initial state.

This was on #170.  The issue no longer exists with your last commit #172

**Comment by LunaTheFoxgirl** [comment] 2023-02-11 20:05
Closing this as solved by #172 then

**Closed by LunaTheFoxgirl** 2023-02-11 20:05 UTC
Labels: bug, enhancement
