### ISSUE TITLE
[BUG] Inconsistent behavior of Flip Deform

### ISSUE THREAD

**Issue by helloar14** [Inochi2D/inochi-creator#209] opened 2023-03-15 13:23 UTC
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

I'm not sure if this is a bug or just me misunderstanding the exact behavior of flip deform, but here are the details:

- Copying and pasting deform, then flipping it results in a definitely wrong shape.
- Resetting the deformation first (right-click -> reset), then pasting the deformation, then flipping it results in a correctly flipped mesh.

### Reproduction

1. Copy deformation from a parameter axis point.
2. Paste in another axis point.
3. Flip the deformation (this results in wrong flipped mesh shape).
4. Reset the deformation.
5. Paste the deformation again.
6. Flip the deformation again (now this produces correctly flipped deformation).

### System Architecture

x86_64

### Operating System

Windows

### Version

5bc52e5

**Comment by seagetch** [comment] 2023-03-15 13:49
"flip deform" is not implemented correctly compared with similar operation such as "mirrored autofill" and "set from mirror".
unless object is selected and becomes active, this operation will fail (for now.)
Does this explain the cause of the issue you reported?

Should be fixed anyway.

**Comment by helloar14** [comment] 2023-03-15 14:23
Yeah, I have no problem with it (because as explained above, I know how to get it right, or at least what I expected to be right), just letting the team know.

**Comment by seagetch** [comment] 2023-03-15 14:26
I submitted fix patch PR#210.
I recommend to use combination of flip pair and "Set from mirror" operation instead of "Flip Deform" in general, though.

**Comment by LunaTheFoxgirl** [comment] 2023-03-16 04:21
Fixed by #210

**Closed by LunaTheFoxgirl** 2023-03-16 04:21 UTC
Labels: bug
