### ISSUE TITLE
[BUG] Crash when model is loaded with missing parts for flip pairing

### ISSUE THREAD

**Issue by Almarane** [Inochi2D/inochi-creator#290] opened 2023-06-29 22:00 UTC
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

Opening the "Flip Pairing" window crashes Inoshi Creator when on a loaded model with missing parts.

### Reproduction

1. In Inochi Creator, add two elements (element A and element B) to a flip pairing using the Flip Pairing window.
2. In the "Nodes" list, delete element A
3. Save the project
4. Open the project (either directly open the project without closing it, or close the project or Inochi Creator then open the project)
5. Open the Flip Pairing window -> Inochi Creator crashes silently.

### System Architecture

None

### Operating System

Windows

### Version

v0.8.0

### Additional Context

No logs are provided by the app.

Note that the bug does not happen until you do step 4 of the reproduction process. Reopening the Flip Pairing window without reopening the project works fine.

**Comment by seagetch** [comment] 2023-06-30 14:27
I couldn't reproduce this bug myself with latest commit.
Does anyone confirm this?

**Comment by LunaTheFoxgirl** [comment] 2023-06-30 16:57
Can't reproduce the issue, closing for now until we have a way to reproduce it.

**Closed by LunaTheFoxgirl** 2023-06-30 16:57 UTC
Labels: Not reproducible
